# Generated by Django 6.0.2 on 2026-02-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0003_formquestion_consider_for_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=100)),
                ('options_snapshot', models.JSONField(blank=True, null=True)),
                ('form_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form_management.formquestion')),
            ],
        ),
    ]
