# Generated by Django 6.0.2 on 2026-02-26 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_management', '0004_questionsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsnapshot',
            options={'ordering': ['-created_dt']},
        ),
        migrations.AddField(
            model_name='questionsnapshot',
            name='created_by',
            field=models.IntegerField(blank=True, help_text='References user ID from vidyanvesha_core database', null=True),
        ),
        migrations.AddField(
            model_name='questionsnapshot',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 26, 8, 1, 6, 463873, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionsnapshot',
            name='institute_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='questionsnapshot',
            name='university_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='questionsnapshot',
            name='updated_by',
            field=models.IntegerField(blank=True, help_text='References user ID from vidyanvesha_core database', null=True),
        ),
        migrations.AddField(
            model_name='questionsnapshot',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
