"""
Django settings for vidyanvesha_form project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add vidyanvesha_core to Python path (only for local development)
# For production on different VM, this won't be used
# Commented out to use local commons module instead of external one
# VIDYANVESHA_CORE_PATH = os.getenv(
#     'VIDYANVESHA_CORE_PATH',
#     str(Path(__file__).resolve().parent.parent.parent / 'vidyanvesha_core')
# )
# if os.path.exists(VIDYANVESHA_CORE_PATH) and VIDYANVESHA_CORE_PATH not in sys.path:
#     sys.path.insert(0, VIDYANVESHA_CORE_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9$@4v#$p-s5we5e+5lgrq)%9f4jfaab^(6=jzgg6u!=emmh@(4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','ekamvistar.com', 'www.ekamvistar.com', '127.0.0.1', 'localhost']


env_allowed_hosts = os.getenv("ALLOWED_HOSTS")
if env_allowed_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in env_allowed_hosts.split(",") if host.strip()])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # CORS
    'corsheaders',
    # REST Framework
    'rest_framework',
    'django_filters',
    # Local apps
    'commons',
    'form_management',
    # 'account_management',  # Accessed via secondary database (SQL), no local module needed
    # 'universities_management',
    # 'institutes_management',
    # DO NOT include other secondary apps here!
    # They are accessed via models imports and router, not migrations
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vidyanvesha_form.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vidyanvesha_form.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vidyanvesha_form',
        'USER': 'postgres',
        'PASSWORD': 'Abcde@12345',
        'HOST': 'localhost',  # Local PostgreSQL
        'PORT': '5432',
    },
    'secondary': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'vidyanvesha_core',
        'USER': 'vidyanvesha_core_db_user',
        'PASSWORD': 'Abcdef@123456',
        'HOST': 'ec2-34-234-69-85.compute-1.amazonaws.com',  # AWS RDS endpoint
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = ['vidyanvesha_form.router.SecondaryDatabaseRouter']

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'form_management.authentication.FirebaseAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# Firebase Configuration
# https://firebase.google.com/docs/database/admin/start

import firebase_admin
from firebase_admin import credentials

FIREBASE_CREDENTIALS_PATH = os.environ.get(
    'FIREBASE_CREDENTIALS_PATH',
    os.environ.get(
        'GOOGLE_APPLICATION_CREDENTIALS',
        os.path.join(BASE_DIR, 'config', 'firebase_service_account.json')
    )
)

# Initialize Firebase - more robust with better error handling
_firebase_initialized = False
_firebase_init_error = None

def _initialize_firebase():
    """Initialize Firebase Admin SDK with detailed error handling"""
    global _firebase_initialized, _firebase_init_error
    
    try:
        if firebase_admin._apps:
            _firebase_initialized = True
            return True
        
        # Try multiple paths
        paths_to_try = [
            FIREBASE_CREDENTIALS_PATH,
            os.path.join(BASE_DIR, 'config', 'firebase_service_account.json'),
            '/app/config/firebase_service_account.json',  # Docker path
            '/home/ubuntu/vidyanvesha_form/config/firebase_service_account.json',  # Likely prod path
        ]
        
        for path in paths_to_try:
            if path and os.path.exists(path) and os.path.getsize(path) > 0:
                try:
                    cred = credentials.Certificate(path)
                    firebase_admin.initialize_app(cred)
                    _firebase_initialized = True
                    # print(f"[OK] Firebase initialized from: {path}")
                    return True
                except Exception as e:
                    # print(f"WARNING: Failed to initialize from {path}: {str(e)}")
                    continue
        
        # If we get here, no credentials found
        _firebase_init_error = f"No valid Firebase credentials found in paths: {paths_to_try}"
        # print(f"[ERROR] {_firebase_init_error}")
        _firebase_initialized = False
        return False
        
    except Exception as e:
        _firebase_init_error = str(e)
        # print(f"[ERROR] Firebase initialization error: {e}")
        _firebase_initialized = False
        return False

# Try to initialize on startup
_initialize_firebase()

# CORS Configuration for Frontend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://edu-world-frontend.vercel.app",
    "https://core.vidyanvesha.ekamvistar.com",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
