export const API_CONTS = {
    FORMS: {
        LIST: "/forms",
        CREATE: "/forms",
        UPDATE: "/forms/:id",
        DELETE: "/forms/:id",
        GET: "/forms/:id",
    },
    RESPONSES: {
        LIST: "/form-responses/",
        CREATE: "/form-responses/",
        UPDATE: "/form-responses/:id/",
        DELETE: "/form-responses/:id/",
        GET: "/form-responses/:id/",
    },
    SETTINGS: {
        LIST: "/settings",
        CREATE: "/settings",
        UPDATE: "/settings/:id",
        DELETE: "/settings/:id",
        GET: "/settings/:id",
    },
    FORM_SECTIONS: {
        LIST: "/form-sections/",
        CREATE: "/form-sections/",
        UPDATE: "/form-sections/:id/",
        DELETE: "/form-sections/:id/",
        GET: "/form-sections/:id/",
    },
    QUESTION_POOLS: {
        LIST: "/question-pools/",
        CREATE: "/question-pools/",
        UPDATE: "/question-pools/:id/",
        DELETE: "/question-pools/:id/",
        GET: "/question-pools/:id/",
    },
    FORM_QUESTIONS: {
        LIST: "/form-questions/",
        CREATE: "/form-questions/",
        UPDATE: "/form-questions/:id/",
        DELETE: "/form-questions/:id/",
        GET: "/form-questions/:id/",
    },
    FORM_ANSWERS: {
        LIST: "/form-answers/",
        CREATE: "/form-answers/",
        UPDATE: "/form-answers/:id/",
        DELETE: "/form-answers/:id/",
        GET: "/form-answers/:id/",
    },
    QUESTION_ANALYTICS: {
        LIST: "/question-analytics/",
        CREATE: "/question-analytics/",
        UPDATE: "/question-analytics/:id/",
        DELETE: "/question-analytics/:id/",
        GET: "/question-analytics/:id/",
    },
    QUESTION_SNAPSHOTS: {
        LIST: "/question-snapshots/",
        CREATE: "/question-snapshots/",
        UPDATE: "/question-snapshots/:id/",
        DELETE: "/question-snapshots/:id/",
        GET: "/question-snapshots/:id/",
    },
    FILE_UPLOADS: {
        LIST: "/file-uploads/",
        CREATE: "/file-uploads/",
        UPDATE: "/file-uploads/:id/",
        DELETE: "/file-uploads/:id/",
        GET: "/file-uploads/:id/",
    },
    ACCESS_RULES: {
        LIST: "/access-rules/",
        CREATE: "/access-rules/",
        UPDATE: "/access-rules/:id/",
        DELETE: "/access-rules/:id/",
        GET: "/access-rules/:id/",
    },
}